version: '3.1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ywemay/node-rest-shop
    container_name: node-rest-shop
    ports:
      - 86:3000
    volumes:
      - .:/home/node/app
    links:
      - mongosrv
    environment:
      DB_LINK: 'mongodb://someusername:SoM3s3cur3paSS@mongosrv:27017/noderestshop'
      JWT_KEY: "OJB7Ggghsld90hshhd7xf5dgklhaf430394jlsdf04"

  mongosrv:
    image: mongo:4.2.5
    restart: always
    container_name: mongo-container
    environment:
      MONGO_INITDB_DATABASE: 'noderestshop'
      MONGO_INITDB_ROOT_USERNAME: 'someusername'
      MONGO_INITDB_ROOT_PASSWORD: 'SoM3s3cur3paSS'
    volumes:
      - ./init-db/init-mongo.js:/docker-entrypoint-initdb.d/init.js:ro
      - ./data:/data/db
    ports:
      - 27017:27017

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   depends_on:
  #       - mongosrv
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: someusername
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: SoM3s3cur3paSS
  #     ME_CONFIG_MONGODB_PORT: 27017
  #     ME_CONFIG_MONGODB_SERVER: mongosrv
